# Generated by Django 2.0.5 on 2019-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assitents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
    ]
